name: bionlp
dependencies:
- python>=3.4
- cycler
- decorator
- entrypoints
- freetype
- gensim
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- libpng
- markupsafe
- matplotlib
- mistune
- nbconvert
- nbformat
- notebook
- numpy>=1.10.3
- openssl
- pandas
- path.py
- pexpect
- pickleshare
- pip
- ptyprocess
- pydot-ng
- pygments
- pyparsing
- pyqt
- python-dateutil
- pytz
- pyyaml
- pyzmq
- qt
- qtconsole
- readline
- requests
- scipy
- scikit-learn
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- terminado
- tk
- tornado
- traitlets
- wheel
- xz
- zlib
- pip:
  - keras
  - theano
